# For each service, you'll need to configure two Kubernetes objects—a deployment and a service
# 
# Deployments manage sets of pods to keep the "desired state" of the cluster. 
# Pods are collections of containers. Because they are created and destroyed dynamically,
# services are needed to provide fixed addresses by which to access them. Which pods are 
# targeted by which services, is determined by label selectors.
#
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gcd-deployment
  labels:
    app: gcd
spec:
  selector:
    matchLabels:
      app: gcd
  replicas: 3
  template:
    metadata:
      labels:
        app: gcd
    spec:
      containers:
      - name: gcd
        image: local/gcd
        imagePullPolicy: Never
        ports:
        - name: gcd-service
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gcd-service
spec:
  selector:
    app: gcd
  ports:
  - port: 3000
    targetPort: gcd-service